name: create release

on:
  issues:
    types:
      - labeled

jobs:
  create_release:
    if: github.event.label.name == 'approve release' && contains(github.event.issue.labels.*.name, 'release candidate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release-candidate
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: yarn install
      - name: Release commit
        run: |
          yarn release
          echo "NEW_TAG=$(git describe)" >> $GITHUB_ENV
      - name: Create CHANGELOG
        run: yarn changelog
      - name: Push release
        run: |
          git push origin $NEW_TAG
          git checkout master
          git cherry-pick $NEW_TAG
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          body_path: ./CURRENT_CHANGELOG.md
      - name: Craete Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'chore(release): ${{ env.NEW_TAG }}'
          branch: 'merge-release-${{ env.NEW_TAG }}'

