name: publish release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo This branch is not release-candidate.
        exit 1
        if: contains(github.ref, 'release-candidate')
      - run: echo This is correct

