name: exit test

on:
  workflow_dispatch:

jobs:
  exit_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This branch is not release-candidate.
          exit 1
        if: !contains(github.ref, 'release-candidate')
      - run: echo This is correct

