name: start release

on:
  workflow_dispatch:

jobs:
  start_release:
    runs-on: ubuntu-latest
    env:
      RESULT_PATH: /tmp/result.txt
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Git Config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Prepare Release
        run: |
          BASE_TAG=v$(npx -c 'echo "$npm_package_version"')
          git checkout $BASE_TAG
          git merge --no-edit ${{ github.ref }}
          yarn install
      - name: Release Dry Run
        run: |
          echo "Dry Run Log:
          \`\`\`
          $(yarn release --dry-run)
          \`\`\`" >> ${{ env.RESULT_PATH }}
      - name: Push Branch
        run: |
          git checkout -b release-candidate
          git push origin release-candidate
      - name: Create Issue
        id: create-issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Release candidate
          content-filepath: ${{ env.RESULT_PATH }}
          labels: release candidate


