name: title check


on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title_lint:
    runs-on: ubuntu-latest
    steps:
      - name: check title
        id: check-title
        run: |
          if [[ ${{ github.event.title }} =~ ^(feat|fix|docs|chore|style|refactor|perf|test):\s.*$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: exit
        if: steps.check-tag.outputs.match == 'true'
        run: exit 1

