name: Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  conventional_commits:
    runs-on: ubuntu-latest
    steps:
      - name: check title
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^(feat|fix|docs|chore|style|refactor|perf|test)!?:[[:space:]] ]]; then
              echo ::set-output name=ok::true
          else
              echo "エラーです"
              echo "::error::エラー"
              exit 1
          fi

