name: title check


on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title_lint:
    runs-on: ubuntu-latest
    steps:
      - name: check title
        id: check-title
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

